name: flutterApp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.3+3

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
  # mapbox_gl: ^0.16.0
  latlong2:
  image: ^4.3.0
  google_fonts: ^6.2.1
  web_socket_channel: ^3.0.1
  uuid: ^4.5.1
  get_thumbnail_video: ^0.7.3
  permission_handler: ^12.0.0
  mime: ^2.0.0
  chewie: ^1.2.2
  geolocator:
  flutter_polyline_points: ^2.1.0
  http:
  flutter_dotenv: ^5.0.2
  material_floating_search_bar_2: ^0.5.0
  provider: ^6.0.5
  phosphor_flutter: ^2.0.1
  shimmer: ^3.0.0
  country_picker: ^2.0.20
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  curved_navigation_bar: ^1.0.6

  # mapbox_gl: ^0.16.0
  mapbox_maps_flutter: ^2.3.0
  youtube_player_iframe:
  youtube_player_flutter:
  universal_io: ^2.2.2
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon1.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
